### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Diederik-CDDT** [marclelijveld/External-Tools-Model-Documentation#1]
Hi Marc, I love the idea of a documenting tool. Already tried another one but to no success. So I was happy to see your anouncement and since I need to deliver some documentation of my last project to a client tomorrow I decided to try your solution immediately. 
I downloaded your 3 files and put the JSON in the appropriate Power BI Desktop folder. The other 2 went to C:\temp, so no alterations. After restarting PBI I noticed the new Icon of your tool in the External Tools ribbon and after opening my client project I hit the button. 
The MS script screen flashed like you describe but then..... silence. When I go the the C:\temp\ folder there are still the 2 files, but yet nothing happens.
Did I miss something in the description? I opened a PBIX file from a synced sharepoint folder on my laptop. I tried another, earlier project on my HDD but here also nothing happens.
So I guess I missed a step in the process, but which?
BR, Diederik

**Comment by bneelon85** [comment]
@Diederik-CDDT 

Is this your computer or is it on a company PC? I did some editing of the Data-Marc_WriteConnectionDetailsToFile.ps1 and Data-Marc_ModelDocumentor.pbitool.json using VS Code because I have my files going to somewhere different than C:\temp. 
Interestingly, I could run the .ps1 from VS Code using the plugin and got further down the line (I'll need to raise another issue in a different thread).

All this to say, I tried running the .ps1 from PowerShell directly and got an Unauthorized Access and was able to confirm that our IT has limited end users ability to run Power Shell Scripts. This may be your issue.

**Comment by marclelijveld** [comment]
Hi Diederik, 

Today I had someone else that has exactly the same as you described. We found the solution for it, which was caused by the execution policies for PowerShell configured on the computer. As far as I know, this is not something I can change in my script, but has everything to do with the setup of your PC or how your company configured it. 

In the end, this resulted in the fact that PowerShell did start, but it didn't execute the script, because this was prevented by the policy. Anyhow, the solution we used was to change the execution policy (which is a register thing). 

First thing you can do is Open PowerShell and run this: Get-ExecutionPolicy -List 
That will show you the current setup of the policies. Most probably, everything is set to undefined at this moment. We fixed the issue by changing this to Unrestricted for the current user as described in this article: 
https://winaero.com/blog/change-powershell-execution-policy-windows-10/ 

But please know, it is completely up to you if you want to do this our not, as this applies a change in your register. It's all on your own risk. 

Hope this helps anyway :) 

Cheers, 
Marc

**Comment by Diederik-CDDT** [comment]
@bneelon85 
Hi Bobby, thanks for your reply. I'm using a private (no restricted) laptop, a Microsoft Surfacebook 2. So I think there must be something els. I see Marc maybe has anothe solution so I will dive into that. Thanks again.

**Comment by Diederik-CDDT** [comment]
@marclelijveld 
Marc, thanks for your reply, I will have to think about that. Playing with the register is not one of my favourite topics :-(.
This is my primary working laptop with all my client files...... 
I will carefully read the powershell article......
BR Diederik

**Comment by marclelijveld** [comment]
Hi Diederik, 
Thanks for the reply. Definitely consider if this is what you want to do. Though, I think you might run into this problem with other stuff as well at another moment. This is a general PowerShell thing, so other scripts might have the same issue for you. 

As you said, read the article carefully so you can decide yourself what to do. 

For now, I will mark this topic as closed.
