### ISSUE TITLE
Unable to load external tool

### ISSUE THREAD

**Issue by mhammons** [marclelijveld/External-Tools-Model-Documentation#16]
Hello, 

Getting the above error. I do have other tools installed and load fine. Error says json file is incorrect. 

I have the latest version of PBI Desktop 2.92.943.0 64-bit (April 2021) and using 1.2 of the json file.

The other two files are in the c:\temp folder.

![pbitool json wrong](https://user-images.githubusercontent.com/36681041/116421428-d1ed5d00-a80c-11eb-8b70-a438b78a5d44.png)

**Comment by jodeja** [comment]
Same here (version 2.93.981.0 64-bit (mei 2021))

**Comment by marclelijveld** [comment]
Hi @jodeja 

Please check if you copied the JSON file correctly. I've had people in the past flagging the same issue, but they copied entire HTML code from GitHub rather than just the JSON. 

--Marc

**Comment by marclelijveld** [comment]
Model Documenter v2.0.0 has just been released. Please check [this page](https://data-marc.com/model-documenter/) to get the latest version. All pending issues should be fixed by now. Also, v2.0.0 has a new easy installer, which helps you to put all files in the correct format in the right location. 
Also see pull request #21
