### ISSUE TITLE
Duplicate found in a perspective SSAS Tabular 

### ISSUE THREAD

**Issue by Marcorus** [marclelijveld/External-Tools-Model-Documentation#29]
Hi, 
When connecting to one my SSAS Tab cube via Power BI Dataset, we have encountered this error.

![image](https://user-images.githubusercontent.com/19165576/150558672-387e356c-a05b-4c67-a73c-5ae5538b89a2.png)

**Comment by dmtvasin** [comment]
I have same mistake

**Comment by marclelijveld** [comment]
Thanks for bringing this up @Marcorus and @dmtvasin 
I'll investigate what exactly went wrong here. I wasn't even aware that it is possible to have duplicate Perspective names. As a quick fix, you can remove the conflicting relationship, since there is also no reporting on perspectives at this moment in the model documenter.

**Comment by marclelijveld** [comment]
Fixed with release of version v2.1.0 and merge #48
