### ISSUE TITLE
 Change data source

### ISSUE THREAD

**Issue by dmtvasin** [marclelijveld/External-Tools-Model-Documentation#30]
Hello Marc!
Thank you for your model documentation. Can I change data source from local file (C:\Power BI Model Documenter) to Azure Analysis Services, because I want to deploy this PBI to the cloud and configure "Connect Live". I understand that need get DaxVpaView.json and DaxModel.json from Azure Analysis Services without saving on the local disk, but don't undestand how it do.

 If you can suggest some other option please tell about it

**Comment by marclelijveld** [comment]
Hi @dmtvasin, 
Not sure if I fully understand your question. Do you want to save the model documentation to an AAS instance? 

Today, if your Power BI Desktop is connected to AAS, you can already document the AAS model. Only an additional pop-up for authentication will appear during tool execution. 

Please elaborate :) 
--Marc

**Comment by dmtvasin** [comment]
@marclelijveld 
Hi Marc, I want deploy this pbix on the cloud in workspace and configure automatic update every day this pbix apps

**Comment by marclelijveld** [comment]
Okay, why exactly do you want to do that? Cause the model documenter is reporting meta data, such as Power Query expressions, measure expressions etc. It is not very likely that the meta data will change in the service, unless you change elements over XMLA. 

At this moment refreshing in the service is not supported, due to the fact that the Model Documenter relies on a local generated VPAX export which is placed in _C:\Power BI Model Documenter_ As this location is not accessible from the service, you cannot refresh it.
