### ISSUE TITLE
Refresh doesn't appear to update the PBI Documenter model with changes made in the PBI source model

### ISSUE THREAD

**Issue by jamesfgibson** [marclelijveld/External-Tools-Model-Documentation#35]
How can I refresh my documented data model after making changes in the source data model?
The data source setting  in the documented model is defaulted to C:\Power BI Model Documenter.

**Comment by marclelijveld** [comment]
Hi @jamesfgibson, there is no way to refresh the model documentation, since at tool execution there is a one-time vpax file generated from your data model. This will remain the only version of your model documentation, untill you run the tool again. 

For more details, I recommend to read [What does the Model Documenter do during execution](https://github.com/marclelijveld/External-Tools-Model-Documentation/wiki/2.-FAQ#what-does-the-model-documenter-do-during-execution) in the Wiki on this page. This page elaborates on the exact working of the tool where the location of the source _C:\Power BI Model Documenter_ is clarified as well. 

--Marc
