### ISSUE TITLE
Combining several dataset models into one report

### ISSUE THREAD

**Issue by JoyHackett** [marclelijveld/External-Tools-Model-Documentation#41]
Marc,

First, I want to thank you for providing this fantastic tool. I am absolutely loving the flexibility and excited to finally have dataset documentation.

As for this question/request...I currently support 16 reports.  I would like to run the Model Documenter for each and combine all the models into one dataset so I can report on all 16 models in one documentation report.  Do you have any suggestions on how to accomplish this? 

Picture of redesigned PBIT file as tax:
![image](https://user-images.githubusercontent.com/17420434/173471618-0fd40a8c-dbc3-4e4d-85a8-9d318156d153.png)

Thanks, Joy

**Comment by marclelijveld** [comment]
Hi @JoyHackett 
Thanks for reaching out! I'm happy to hear you're extensively using the tool! :) 
Unfortunately, today the tool does not support to be run over multiple datasets/reports. That is because the back-end of the tool generates a vpax file for every model. 
What could potentially be a way to explore the possibility, is to generate multiple vpax files manually (using DAX Studio for example) or using the model documenter and copy-paste the vpax files to a different location. Based on that, you can adjust the PowerQuery logic of the Power BI Template file, to read multiple vpax files at the same time. The challenge will most likely be in the relationships between tables, as they're not all based on unique values. So some values might repeat themselves for other models with might cause a many-to-many relationship. 

Hope this helps, let me know if I can further assist. 
--Marc

**Comment by marclelijveld** [comment]
Closing this one, as it's open for almost 2y.
