### ISSUE TITLE
Additional feature request - Report Name

### ISSUE THREAD

**Issue by NickA01** [marclelijveld/External-Tools-Model-Documentation#44]
Would be great if the report name could be included on the info tab?

**Comment by marclelijveld** [comment]
Thanks for your comment @NickA01. At this moment the model documenter is depending on the meta data of the data model, which does not include the reportname / file name. I'll list this item as enhancement to see if we can make this happen in the future.

**Comment by marclelijveld** [comment]
Fixed with release of version v2.1.0 and merge #48  
I did all I can do now, as in a local PBI model, the model name is a guid. If you connect PBI desktop using the AAS connector to existing data models (could be AAS or existing PBI Premium models over XMLA) you will see the name is fetched automatically.
