### ISSUE TITLE
Connect Data Model Documenter Report Directly to the Data Model, not a separate connection

### ISSUE THREAD

**Issue by jkiseeva** [marclelijveld/External-Tools-Model-Documentation#53]
Hi! 

I have read your article about connecting the Power BI Model Documenter to existing data models in the Power BI Service or Analysis Services (https://data-marc.com/2022/11/22/connect-the-power-bi-model-documenter-to-existing-data-models-in-the-power-bi-service-or-analysis-services/), and followed the steps. 

I was hoping it would allow me to achieve my goal to connect the model documenter report to the data model dataset such that whenever updates are applied to the dataset, the data model documenter file updates automatically to reflect these updates. 

However, when I ran the model documenter report and published it to a workspace in the Power BI Service, I noticed that in the "lineage view" of the workspace, instead of the model documenter report being connected to the data model (as I had expected), something different happened.  Below the data model and all of its reports, I saw a new sequence of Source Folder -> Model Documenter Dataset -> Model Documenter Report was added.  Please see the "current state" and "desired state" screenshots to better understand what happened. 

Moreover, when I tried to refresh the data model dataset, I got a "Something went wrong, your data gateway (personal mode) is offline or could not be reached. Please try again later or contact support." error message. 

I would like to know if there is a way to connect the data model documenter report directly, as illustrated in the "desired state" attachment. 

**Current State:**
![current_state](https://user-images.githubusercontent.com/62075437/215525975-19517833-4267-4bab-ae07-ebfdf3ffd760.jpg)

**Desired State:**
![desired_state](https://user-images.githubusercontent.com/62075437/215525973-ec430b90-459f-44f7-b6ba-6017beb2300f.jpg)

**Comment by marclelijveld** [comment]
Hi @jkiseeva 

Unfortunately, this is not possible at the moment due to the logic in the application that is needed to run the tool. The tool generates a VPAX file, which is saved locally on your machine. That also clarifies the error when you try to refresh. 

The current setup of the model documenter completely relies on the VPAX files and therefore the desired state you described cannot be achieved. Also, keep in mind that the model documenter only describes metadata, which is limited adapted to change. Therefore, the use case of refreshing the model documenter report is limited. 
In case you want something like this, consider building a dataset directly on top of an XMLA endpoint of Power BI Premium where all logic is captured in the data model. 

Given I will not work on a fix right now, in line with above explanation, I will close this issue for now. 
--Marc
