### ISSUE TITLE
Facing below issue while running the Model Documenter

### ISSUE THREAD

**Issue by slabhe** [marclelijveld/External-Tools-Model-Documentation#59]
File or Folder: We couldn't find the folder 'C:\Power BI Model Documenter\ModelDocumenter.vpax'.

**Comment by marclelijveld** [comment]
Can you please provide more context @slabhe ? When are you running into this error, what is it you try to do when you got this error? Which version of the model documenter are your running?

**Comment by slabhe** [comment]
Please find my reply below in bold
When are you running into this error>> **When I  try to run the ModelDocumentationTemplate_v2.1.0.pbit**
when you got this error? **While loading tables and queries in ModelDocumentationTemplate_v2.1.0.pbit**
**Using Version 2.1.0**

**Comment by marclelijveld** [comment]
Okay, so I assume from your description that you try to directly open the Power BI template file, instead of running the model documenter from the ribbon in Power BI desktop. When you run the tool from desktop, a process is being kicked-off to generate the file to which the error refers. 

I suggest you run the model documenter from the ribbon and then try again.

**Comment by marclelijveld** [comment]
CLosing this one, as it's open for a long time already.
